name: vt
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - scikit-learn=1.3.2
  - tensorboard
  - chardet
  - pip:
      - torch==2.2.0
      - transformers==4.41.1
      - datasets
      - Pillow
      - huggingface-hub==0.23.3
      - accelerate==0.27.2
